field: e84f8add-70a4-4227-835b-be62710af7e2 # Matrix
fieldLayouts:
  f49e7efc-e7fe-416f-ab1c-eb2765b940d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 16f54560-82dd-48ec-80f4-1288baf410fa # testo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 070ae3fe-6079-479d-b5f3-b765c7a20f69
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497a8ec3-9f9a-4947-a0b1-b9404c1c59f3 # entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e758ecc-ab92-41be-97a4-563e1adf764f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f5ce121-9e6f-47c7-9786-c0070f0e4f96
        userCondition: null
fields:
  16f54560-82dd-48ec-80f4-1288baf410fa: # testo
    columnSuffix: mnpawajh
    contentColumnType: text
    fieldGroup: null
    handle: testo
    instructions: null
    name: testo
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  497a8ec3-9f9a-4947-a0b1-b9404c1c59f3: # entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: null
    name: entry
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: blocco
name: Blocco
sortOrder: 1
