fieldLayouts:
  4d8be229-007f-4089-829d-4209a3df545a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 94b762c6-5616-4bf9-940f-698d64533a52
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b54c64eb-29bf-43ea-a2bf-49350eda4984
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 8cf230db-3044-4cb7-aeb7-ed3578d3485d # Categorie
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
