columnSuffix: null
contentColumnType: string
fieldGroup: 684cc56c-13ac-45b3-807a-2077cfac261a # Common
handle: related
instructions: null
name: Related
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:0940e175-610b-48f9-98b5-9de48d6c4027' # Categorie
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
