dateModified: 1703173327
email:
  fromEmail: michele@dellanesta.it
  fromName: 'Test Docker'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    04d63fa5-e717-48bf-b8f8-340293fffda5: Test # Test
    8cf230db-3044-4cb7-aeb7-ed3578d3485d: Categorie # Categorie
    16f54560-82dd-48ec-80f4-1288baf410fa: testo # testo
    218ba258-0fdf-4523-aacc-3b77f78e0b41: Related # Related
    497a8ec3-9f9a-4947-a0b1-b9404c1c59f3: entry # entry
    684cc56c-13ac-45b3-807a-2077cfac261a: Common # Common
    943a0c4d-6ca1-44ff-9a54-21837fcee488: Default # Default
    2453ab96-1f4f-4612-ab9b-d1e5203ac208: Homepage # Homepage
    06350fbe-8b46-4ebf-bd0d-bb21379f39da: 'Test 2023' # Test 2023
    adb5b625-1b31-4da6-81ae-c8f553cdcd9b: Default # Default
    cb3eb1f1-99e6-4d58-9e62-aae04d9497f5: Homepage # Homepage
    d636c4e4-6378-4522-8367-33f665f4a711: 'Test Docker' # Test Docker
    e8b64a7b-ad2f-426b-ba3c-3cbe058f4746: 'Test Docker' # Test Docker
    e84f8add-70a4-4227-835b-be62710af7e2: Matrix # Matrix
    e679f241-0434-4caa-aab9-a8cb07cc0a72: Blocco # Blocco
    f095057b-12b7-426e-bba9-77a4e6e2c1ce: Testo # Testo
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  freeform:
    edition: lite
    enabled: true
    schemaVersion: 4.2.7
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Test Docker'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
